name: 'Compile GAP package documentation'
description: 'Compile documentation with or without latex'
inputs:
  use-latex:
    description: 'if true, then install and use latex'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: "Install TeX Live"
      shell: bash
      run: |
        if [ ${{ inputs.use-latex }} == 'true' ]; then
          packages=(
            texlive-latex-base
            texlive-latex-recommended
            texlive-latex-extra
            texlive-extra-utils
            texlive-fonts-recommended texlive-fonts-extra
          )
          sudo apt-get install "${packages[@]}"
        fi

    - name: "Compile documentation"
      shell: bash
      run: |
        if [ -f "makedoc.g" ]; then
          $HOME/gap/bin/gap.sh -l "$PWD/gaproot;" --quitonbreak makedoc.g -c "QUIT;"
        elif [ -f "doc/make_doc" ]; then
           cd doc
           ./make_doc
        else
          echo "no makedoc.g file or doc/make_doc script found!"
          exit 1
        fi
      env:
        SOURCE_DATE_EPOCH: 0 # prevent time stamps in generated PDF
